-- MySQL Script generated by MySQL Workbench
-- Sex 13 Out 2017 20:51:21 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema unimap
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema unimap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `unimap` DEFAULT CHARACTER SET utf8 ;
USE `unimap` ;

-- -----------------------------------------------------
-- Table `unimap`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimap`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `type` CHAR(1) NULL DEFAULT 'A',
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_unique` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimap`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimap`.`rooms` (
  `cod_sala` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimap`.`disciplines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimap`.`disciplines` (
  `cod_disc` CHAR(6) NOT NULL,
  `name` VARCHAR(255) NULL,
  `department` VARCHAR(255) NULL DEFAULT '',
  PRIMARY KEY (`cod_disc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimap`.`authorizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimap`.`authorizations` (
  `user` VARCHAR(11) NOT NULL,
  `teacher` VARCHAR(11) NOT NULL,
  `room` INT NOT NULL,
  PRIMARY KEY (`user`, `teacher`, `room`),
  INDEX `fk_users_has_rooms_rooms1_idx` (`room` ASC),
  INDEX `teacher` (`teacher` ASC),
  CONSTRAINT `authorizations_ibfk_1`
    FOREIGN KEY (`user`)
    REFERENCES `unimap`.`users` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `authorizations_ibfk_2`
    FOREIGN KEY (`teacher`)
    REFERENCES `unimap`.`users` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_has_rooms_rooms1`
    FOREIGN KEY (`room`)
    REFERENCES `unimap`.`rooms` (`cod_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimap`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimap`.`notifications` (
  `user` VARCHAR(11) NOT NULL,
  `room` INT NOT NULL,
  PRIMARY KEY (`user`, `room`),
  INDEX `fk_users_has_rooms_rooms2_idx` (`room` ASC),
  CONSTRAINT `fk_users_has_rooms_rooms2`
    FOREIGN KEY (`room`)
    REFERENCES `unimap`.`rooms` (`cod_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `notifications_ibfk_1`
    FOREIGN KEY (`user`)
    REFERENCES `unimap`.`users` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `unimap`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `unimap`.`reservations` (
  `teacher` VARCHAR(11) NOT NULL,
  `room` INT NOT NULL,
  `discipline` CHAR(6) NOT NULL,
  `initialTime` INT NOT NULL,
  `finalTime` INT NOT NULL,
  `weekDay` VARCHAR(9) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`teacher`, `room`, `discipline`),
  INDEX `fk_users_has_rooms_rooms3_idx` (`room` ASC),
  INDEX `fk_users_has_rooms_disciplines1_idx` (`discipline` ASC),
  CONSTRAINT `fk_users_has_rooms_disciplines1`
    FOREIGN KEY (`discipline`)
    REFERENCES `unimap`.`disciplines` (`cod_disc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_rooms_rooms3`
    FOREIGN KEY (`room`)
    REFERENCES `unimap`.`rooms` (`cod_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `reservations_ibfk_1`
    FOREIGN KEY (`teacher`)
    REFERENCES `unimap`.`users` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
